name: Python Package Test Publisher
on:
  push:
    tags:
      - "v*.*.*-beta"
      - "v*.*.*-alpha"
      - "v*.*.*-alpha-*"
      - "v*.*.*-beta-*"
      - "v*.*.*-rc-*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.TEST_PYPI }}
          repository_name: "morty-portal-gun"
          repository_url: "https://test.pypi.org/legacy/"