name: Python Package Test Publisher
on:
  push:
    tags:
      - "v[9-0]+.[9-0]+.[9-0]+-beta"
      - "v[9-0]+.[9-0]+.[9-0]+-alpha"
      - "v[9-0]+.[9-0]+.[9-0]+-alpha-[9-0]+"
      - "v[9-0]+.[9-0]+.[9-0]+-beta-[9-0]+"
      - "v[9-0]+.[9-0]+.[9-0]+-rc-[9-0]+"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.13
        with:
          pypi_token: ${{ secrets.TEST_PYPI }}
          repository_name: "morty-portal-gun"
          repository_url: "https://test.pypi.org/legacy/"